dataset_id: br_ms_cnes

table_id: profissional

# Descreva a tabela. Essas são as primeiras frases que um usuário vai ver.
# Você não precisa ser muito conciso. Sinta-se a vontade para dar exemplos de
# como usar os dados.
# Se souber, liste também aplicações: pesquisa, apps, etc. que usem os dados.,
description:

# A máxima unidade espacial que a tabela cobre.
spatial_coverage:

# Anos cobertos pela tabela.
# Preencher como lista de intervalos.
# Exemplo: 1995(1)2019.
temporal_coverage:
          - 2005
          - 2006
          - 2007
          - 2008
          - 2009
          - 2010
          - 2011
          - 2012
          - 2013
          - 2014
          - 2015
          - 2016
          - 2017
          - 2018
          - 2019
          - 2020
          - 2021

# A unidade temporal com qual a tabela é atualizada.
# Opções em 'https://basedosdados.org/api/3/action/bd_available_options'
update_frequency:

# Entidade representada por cada linha.
# Opções em 'https://basedosdados.org/api/3/action/bd_available_options'
entity:

# A unidade temporal representada por cada linha.
# Opções em 'https://basedosdados.org/api/3/action/bd_available_options'
time_unit:

# O conjunto mínimo de colunas identificando cada linha unicamente.
# Preencha com os nomes de colunas.
# Exemplos: id_municipio, ano.
# Pode ser vazio pois certas tabelas não possuem identificadores.
identifying_columns:

last_updated:
    metadata:
    data:
    release:

# Versão da tabela. Seguindo o padrão de semantic versioning.
# Exemplo: v1.1.3
version: ''

# Quem está preenchendo esses metadados?
published_by:
    name:
    email:
    github_user:
    website:
    ckan_user:

# Qual organização/departamento/pessoa tratou os dados?
# As vezes há um ponto intermediário entre os dados originais e subir na Base dos Dados.
# Se essa pessoa é você, preencha abaixo com suas informações.
data_cleaned_by:
    name:
    email:
    github_user:
    ckan_user:
    website:
    code_url:

# Se houve passos de tratamento, limpeza e manipulação de dados, descreva-os aqui.
data_cleaning_description:

# Url dos dados originais no GCP Storage.
raw_files_url:

# Url dos arquivos auxiliares no GCP Storage.
auxiliary_files_url:

# Url da tabela de arquitetura no GCP Storage.
architecture_url:

# A tabela tem colunas que precisam de dicionário?
# Opções: yes, no.
covered_by_dictionary:

source_bucket_name: basedosdados-dev

project_id_prod: basedosdados-dev

project_id_staging: basedosdados-dev

# Liste as colunas da tabela que representam partições.
# Não esqueça de deletar essas colunas nas tabelas .csv na hora de subir para o BigQuery.
# Isso poupará muito tempo e dinheiro às pessoas utilizando essa tabela.
# Se não houver partições, não modifique abaixo.
partitions: ano,mes,sigla_uf

bdm_file_size:

# Quais são as colunas? Certifique-se de escrever uma boa descrição, as pessoas vão gostar
# para saber sobre o que é a coluna.
# Adicionar todas as colunas manualmente pode ser bastante cansativo, por isso, quando
# inicializando este arquivo de configuração, você pode apontar a função para uma amostra de dados que
# preencherá automaticamente as colunas.
# Algumas colunas existirão apenas na tabela final, você as construirá em `publish.sql`.
# Para esses, defina is_in_staging como False.
# Além disso, você deve adicionar as colunas de partição aqui e definir is_partition como True.
columns:
    - name: ano
      bigquery_type: int64
      description: Ano
      temporal_coverage:
          - 2005
          - 2006
          - 2007
          - 2008
          - 2009
          - 2010
          - 2011
          - 2012
          - 2013
          - 2014
          - 2015
          - 2016
          - 2017
          - 2018
          - 2019
          - 2020
          - 2021
      covered_by_dictionary: no
      directory_column:
          dataset_id: br_bd_diretorios_data_tempo
          table_id: ano
          column_name: ano
      measurement_unit: year
      has_sensitive_data: no
      is_in_staging: false
      is_partition: true
    - name: mes
      bigquery_type: int64
      description: Mes
      temporal_coverage:
          - 2005
          - 2006
          - 2007
          - 2008
          - 2009
          - 2010
          - 2011
          - 2012
          - 2013
          - 2014
          - 2015
          - 2016
          - 2017
          - 2018
          - 2019
          - 2020
          - 2021
      covered_by_dictionary: no
      directory_column:
          dataset_id: br_bd_diretorios_data_tempo
          table_id: mes
          column_name: mes
      measurement_unit: month
      has_sensitive_data: no
      is_in_staging: false
      is_partition: true
    - name: sigla_uf
      bigquery_type: string
      description: Sigla da Unidade da Federação
      temporal_coverage:
          - 2005
          - 2006
          - 2007
          - 2008
          - 2009
          - 2010
          - 2011
          - 2012
          - 2013
          - 2014
          - 2015
          - 2016
          - 2017
          - 2018
          - 2019
          - 2020
          - 2021
      covered_by_dictionary: no
      directory_column:
          dataset_id: br_bd_diretorios_brasil
          table_id: uf
          column_name: sigla_uf
      measurement_unit:
      has_sensitive_data: no
      is_in_staging: false
      is_partition: true
      
    - name: id_municipio
      bigquery_type: string
      description: ID Município IBGE - 7 Dígitos
      temporal_coverage:
      covered_by_dictionary: yes
      directory_column:
          dataset_id: br_bd_diretorios_brasil
          table_id: municipio
          column_name: id_municipio
      measurement_unit:
      has_sensitive_data:
      is_in_staging: true
      is_partition:
    - name: id_municipio_6
      bigquery_type: string
      description: ID Município IBGE - 6 Dígitos
      temporal_coverage:
      covered_by_dictionary: yes
      directory_column:
          dataset_id: br_bd_diretorios_brasil
          table_id: municipio
          column_name: id_municipio_6
      measurement_unit:
      has_sensitive_data:
      is_in_staging: true
      is_partition:
    - name: id_estabelecimento_cnes
      bigquery_type: string
      description: ID Estabelecimento - CNES
      temporal_coverage:
      covered_by_dictionary: no
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data:
      is_in_staging: true
      is_partition:
    - name: id_municipio_6_residencia
      bigquery_type: string
      description: ID Município da residência do profissional - IBGE 6 Dígitos
      temporal_coverage:
      covered_by_dictionary: yes
      directory_column:
          dataset_id: br_bd_diretorios_brasil
          table_id: municipio
          column_name: id_municipio_6
      measurement_unit:
      has_sensitive_data:
      is_in_staging: true
      is_partition:
    - name: nome
      bigquery_type: string
      description: Nome
      temporal_coverage:
      covered_by_dictionary: no
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data:
      is_in_staging: true
      is_partition:
    - name: cns
      bigquery_type: string
      description: CNS (Cartão Nacional de Saúde) do profissional
      temporal_coverage:
      covered_by_dictionary: no
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data:
      is_in_staging: true
      is_partition:
    - name: cbo_2002
      bigquery_type: string
      description: Código da especialidade do profissional
      temporal_coverage:
      covered_by_dictionary: yes
      directory_column:
          dataset_id: br_bd_diretorios_brasil
          table_id: cbo_2002
          column_name: cbo_2002
      measurement_unit:
      has_sensitive_data:
      is_in_staging: true
      is_partition:
    - name: codigo_registro_conselho
      bigquery_type: string
      description: Número do registro no conselho de classe
      temporal_coverage:
      covered_by_dictionary: no
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data:
      is_in_staging: true
      is_partition:
    - name: codigo_conselho
      bigquery_type: string
      description: Código do conselho de classe
      temporal_coverage:
      covered_by_dictionary: yes
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data:
      is_in_staging: true
      is_partition:
    - name: estabelecimento_terceiro
      bigquery_type: string
      description: O estabelecimento é terceiro
      temporal_coverage:
      covered_by_dictionary: yes
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data:
      is_in_staging: true
      is_partition:
    - name: codigo_vinculo
      bigquery_type: string
      description: Código do vínculo empregatício com o estabelecimento
      temporal_coverage:
      covered_by_dictionary: yes
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data:
      is_in_staging: true
      is_partition:
    - name: vinculo_contratado_sus
      bigquery_type: string
      description: Vínculo empregatício com o estabelecimento- Contratado SUS
      temporal_coverage:
      covered_by_dictionary: yes
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data:
      is_in_staging: true
      is_partition:
    - name: vinculo_autonomo_sus
      bigquery_type: string
      description: Vínculo empregatício com o estabelecimento- Autônomo SUS
      temporal_coverage:
      covered_by_dictionary: yes
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data:
      is_in_staging: true
      is_partition:
    - name: vinculo_outros
      bigquery_type: string
      description: Vínculo empregatício com o estabelecimento- Vínculo não identificado
          (registros de profissionais não SUS e outras situações anômalas)
      temporal_coverage:
      covered_by_dictionary: yes
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data:
      is_in_staging: true
      is_partition:
    - name: atende_sus
      bigquery_type: string
      description: Realiza Atendimento SUS
      temporal_coverage:
      covered_by_dictionary: yes
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data:
      is_in_staging: true
      is_partition:
    - name: atende_nao_sus
      bigquery_type: string
      description: Realiza Atendimento Não-SUS
      temporal_coverage:
      covered_by_dictionary: yes
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit:
      has_sensitive_data:
      is_in_staging: true
      is_partition:
    - name: carga_horaria_outros
      bigquery_type: int64
      description: Carga horária não ambulatorial, nem hospitalar
      temporal_coverage:
      covered_by_dictionary: no
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit: hour
      has_sensitive_data:
      is_in_staging: true
      is_partition:
    - name: carga_horaria_hospitalar
      bigquery_type: int64
      description: Carga horária hospitalar
      temporal_coverage:
      covered_by_dictionary: no
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit: hour
      has_sensitive_data:
      is_in_staging: true
      is_partition:
    - name: carga_horaria_ambulatorial
      bigquery_type: int64
      description: Carga horária Ambulatorial
      temporal_coverage:
      covered_by_dictionary: no
      directory_column:
          dataset_id:
          table_id:
          column_name:
      measurement_unit: hour
      has_sensitive_data:
      is_in_staging: true
      is_partition:

metadata_modified: '2022-01-20T20:37:19.200105'
